services:
  - type: web
    name: sec-10k-fetcher
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: false
    disk:
      name: sec-data
      mountPath: /tmp
      sizeGB: 1 